package main

import (
	"bufio"
	"fmt"
	"log"
	"os"
	"regexp"
	"strings"
	"time"
)

// Opcode represents a single SPC700 instruction definition
type Opcode struct {
	ID   string
	Name string
	Args []string
}

func main() {
	sourcePath := "internal/apu/spc700/instruction.cpp" // Relative to cmd/spc-codegen/ execution? No, let's assume root.
	// Actually we should use the absolute path we found earlier:
	// /Volumes/tmc/go/src/github.com/bsnes-emu/bsnes/bsnes/processor/spc700/instruction.cpp

	// Better: accept args.
	if len(os.Args) < 2 {
		fmt.Println("Usage: spc-codegen <path_to_instruction.cpp>")
		os.Exit(1)
	}
	sourcePath = os.Args[1]

	ops, err := parseOps(sourcePath)
	if err != nil {
		log.Fatal(err)
	}

	generateGo(ops)
}

func parseOps(path string) ([]Opcode, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	var ops []Opcode
	scanner := bufio.NewScanner(f)
	// Regex for op(0x00, Name, ...)
	re := regexp.MustCompile(`op\((0x[0-9a-fA-F]+),\s*([a-zA-Z0-9_]+)(?:,\s*(.*))?\)`)

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if strings.HasPrefix(line, "op(") {
			matches := re.FindStringSubmatch(line)
			if len(matches) > 2 {
				op := Opcode{
					ID:   matches[1],
					Name: matches[2],
				}
				if len(matches) > 3 && matches[3] != "" {
					// Split args by comma, respecting parens if necessary (simple split for now)
					op.Args = strings.Split(matches[3], ",")
					for i := range op.Args {
						op.Args[i] = strings.TrimSpace(op.Args[i])
					}
				}
				ops = append(ops, op)
			}
		}
	}
	return ops, scanner.Err()
}

func generateGo(ops []Opcode) {
	fmt.Printf("// Code generated by spc-codegen. DO NOT EDIT.\n")
	fmt.Printf("// Generated: %s\n\n", time.Now().Format(time.RFC3339))
	fmt.Printf("package spc700\n\n")

	fmt.Printf("// OpcodeNames maps opcode byte to string name\n")
	fmt.Printf("var OpcodeNames = map[uint8]string{\n")
	for _, op := range ops {
		fmt.Printf("\t%s: \"%s\",\n", op.ID, op.Name)
	}
	fmt.Printf("}\n")
}
