// Command spc-codegen generates SPC700 opcode names from bsnes instruction.cpp.
package main

import (
	"bufio"
	"bytes"
	"crypto/sha256"
	"fmt"
	"go/format"
	"io"
	"os"
	"regexp"
	"strconv"
	"strings"
)

type opcode struct {
	id   uint8
	name string
}

func main() { os.Exit(run(os.Args[1:], os.Stdout, os.Stderr)) }

func run(args []string, out, stderr io.Writer) int {
	if len(args) != 1 {
		fmt.Fprintln(stderr, "usage: spc-codegen path/to/instruction.cpp")
		return 2
	}
	source, err := os.ReadFile(args[0])
	if err != nil {
		fmt.Fprintf(stderr, "read source: %v\n", err)
		return 1
	}
	ops, err := parseOps(bytes.NewReader(source))
	if err != nil {
		fmt.Fprintf(stderr, "parse source: %v\n", err)
		return 1
	}
	data, err := generateGo(ops, sha256.Sum256(source))
	if err == nil {
		_, err = out.Write(data)
	}
	if err != nil {
		fmt.Fprintf(stderr, "generate opcodes: %v\n", err)
		return 1
	}
	return 0
}

func parseOps(r io.Reader) ([]opcode, error) {
	var ops [256]opcode
	var seen [256]bool
	count := 0
	re := regexp.MustCompile(`^op\((0x[0-9a-fA-F]+),\s*([a-zA-Z_][a-zA-Z0-9_]*)(?:,.*)?\)\s*$`)
	sc := bufio.NewScanner(r)
	for line := 1; sc.Scan(); line++ {
		s := strings.TrimSpace(sc.Text())
		if !strings.HasPrefix(s, "op(") {
			continue
		}
		m := re.FindStringSubmatch(s)
		if m == nil {
			return nil, fmt.Errorf("line %d: malformed opcode", line)
		}
		id, err := strconv.ParseUint(m[1], 0, 8)
		if err != nil {
			return nil, fmt.Errorf("line %d: opcode id: %w", line, err)
		}
		if seen[id] {
			return nil, fmt.Errorf("line %d: duplicate opcode %02x", line, id)
		}
		seen[id] = true
		ops[id] = opcode{uint8(id), m[2]}
		count++
	}
	if err := sc.Err(); err != nil {
		return nil, err
	}
	if count != 256 {
		return nil, fmt.Errorf("opcode count %d, want 256", count)
	}
	return ops[:], nil
}

func generateGo(ops []opcode, sourceHash [32]byte) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by spc-codegen. DO NOT EDIT.")
	fmt.Fprintf(&b, "// Source: bsnes/processor/spc700/instruction.cpp (SHA-256 %x)\n\n", sourceHash)
	fmt.Fprintln(&b, "package spc700")
	fmt.Fprintln(&b, "// OpcodeNames maps opcode bytes to instruction names.")
	fmt.Fprintln(&b, "var OpcodeNames = map[uint8]string{")
	for _, op := range ops {
		fmt.Fprintf(&b, "0x%02x: %q,\n", op.id, op.name)
	}
	fmt.Fprintln(&b, "}")
	return format.Source(b.Bytes())
}
