package web

const page = `<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>SNES rotation editor</title>
<style>body{font:16px system-ui;background:#171c23;color:#e8edf2;margin:0}header,main{padding:24px;max-width:1100px;margin:auto}main{display:grid;grid-template-columns:1fr 1fr;gap:20px}section{background:#222b36;padding:20px;border-radius:8px}h1{margin:0}small{color:#adb9c6}button,select,input{font:inherit;padding:8px;background:#e8edf2;color:#17202a;border:0;border-radius:4px}pre{white-space:pre-wrap;overflow-wrap:anywhere}td{padding:6px;border-bottom:1px solid #445262;font-size:13px;overflow-wrap:anywhere}table{width:100%;table-layout:fixed}details{margin:12px 0}.experiment{grid-column:1/-1}.experiment img{width:256px;max-width:48%;image-rendering:pixelated}.tag{color:#9ad6c3}#error{color:#ffbdab}@media(max-width:700px){main{display:block}section{margin-bottom:16px}}</style>
<header><h1>Intro rotation</h1><p>Original observations · reversible draft · experiment evidence</p><small id="identity"></small><p id="error"></p></header>
<main><section><h2>Selected object</h2><select id="object"><option value="polygon">Polygon rotation</option><option value="oam">OAM sprite entry</option></select><div id="polygon"><h3>Selected field</h3><select id="fields"></select><pre id="selection"></pre><h3>Observed</h3><p id="observed"></p><h3>Advisory interpretation</h3><p id="inferred"></p></div><div id="oam" hidden><select id="sprites"></select><pre id="spritefields"></pre><h3>Exact observed byte versions</h3><div id="spriteevents"></div><details><summary>Raw byte and event records</summary><pre id="spriteraw"></pre></details><p>Low-table latch origins may be unknown. OAM entry interpretation is not visible pixel ownership.</p></div></section>
<section><h2>Frame</h2><p id="frame"></p><select id="frames"></select><p id="frameidentity"></p><img id="picture" style="max-width:100%;image-rendering:pixelated" hidden alt="Original interpreter capture"><h3>Sprite explanation</h3><p id="sprite"></p></section><section class="experiment"><h2>Parameter draft</h2><label>Initial angular phase <input id="draft" type="number"></label><p id="draftstate">No draft</p><button id="reset">Discard draft</button><p>Draft only. Changing this control does not execute C or alter the original capture.</p><h3>Original baseline</h3><p id="baseline"></p><h3>Source increment experiment</h3><label>Rotation increment <input id="increment" type="number" min="1" max="12" value="6"></label><button id="execute" disabled>Execute compiled C</button><button id="restore" disabled>Restore original increment 5</button><p id="jobstatus">Unavailable until an operator pins a complete-machine experiment.</p><h3>Selected OAM size intervention</h3><label>Size bit <select id="spriteLarge"><option value="false">Clear (small)</option><option value="true">Set (large)</option></select></label><button id="spriteExecute" disabled>Execute selected sprite data edit</button><button id="spriteReset" disabled>Restore captured size bit</button><p id="spriteJobStatus">Unavailable until the operator pins this sprite and checkpoint.</p><p>This changes a packed WRAM size bit after its verified writer; it is not C recovery or visible pixel ownership.</p><select id="jobframes" disabled></select><div><img id="before" style="max-width:48%;image-rendering:pixelated" hidden alt="Original experiment baseline"><img id="after" style="max-width:48%;image-rendering:pixelated" hidden alt="Experimental branch"></div><p id="jobframeidentity"></p><details><summary>Experiment identities and compiled source</summary><pre id="jobidentity"></pre></details></section>
<section><h2>Evidence pins</h2><details><summary>Artifact hashes</summary><pre id="pins"></pre></details><p>Hashes bind retained bytes; they do not establish admission, timing, or pixel ownership.</p></section></main>
<script>
fetch('/api/target').then(r=>{if(!r.ok)throw Error('Target unavailable');return r.json()}).then(m=>{
const t=m.target,o=m.observation,$=id=>document.getElementById(id);
$('identity').textContent=t.id+' · manifest '+m.manifest_sha256;
const fields=[t.parameter.field,...t.effects];fields.forEach((f,i)=>{let n=document.createElement('option');n.value=i;n.textContent=f.name;$('fields').append(n)});
function select(){let f=fields[Number($('fields').value)];$('selection').textContent='WRAM $'+f.address.toString(16).toUpperCase()+' · '+f.bytes+' byte(s)';const edit=$('draft');edit.disabled=Number($('fields').value)!==0||$('object').value==='oam';edit.value='';$('draftstate').textContent=edit.disabled?'Draft unavailable for selected field':'No draft';}select();$('fields').onchange=select;
$('observed').textContent=o.handler_entries+' original intervals, frames '+o.observed_frames.join('–')+', '+o.contiguous_instructions_per_handler+' instructions and '+o.ordered_wram_writes_per_handler+' writes each. '+o.observed_scope;
$('inferred').textContent=t.advisory_crosswalk+' · Names and parameter meaning are advisory.';
const d=$('draft');d.min=t.parameter.minimum;d.max=t.parameter.maximum;
d.oninput=()=>{$('draftstate').textContent=d.value===''?'No draft':d.validity.valid?'Unexecuted draft: '+d.value:'Outside descriptor range';};$('reset').onclick=()=>{d.value='';d.oninput()};
const objects=$('object'),oam=$('oam');
let spriteRunning=false;function updateSprite(){const enabled=!!m.sprite_experiment_id&&objects.value==='oam'&&$('sprites').value===m.sprite_experiment_id&&!spriteRunning;$('spriteExecute').disabled=!enabled;$('spriteReset').disabled=!enabled;$('spriteLarge').disabled=!enabled;}
function object(){let sprite=objects.value==='oam';$('polygon').hidden=sprite;oam.hidden=!sprite;d.disabled=sprite;$('draftstate').textContent=sprite?'Parameter drafting unavailable for OAM selection':'No draft';d.value='';select();if(m.experiment_enabled){$('execute').disabled=sprite;$('restore').disabled=sprite;}updateSprite();}objects.onchange=object;
if(m.sprites){m.sprites.entries.forEach(e=>{let n=document.createElement('option');n.value=e.id;n.textContent='OAM '+e.explanation.sprite;$('sprites').append(n)});function showSprite(){let x=m.sprites.entries.find(e=>e.id===$('sprites').value);if(!x)return;const e=x.explanation;$('spritefields').textContent=JSON.stringify({stable_id:x.id,capture:m.sprites.capture_sha256,host_frame:e.through_host_frame,x:e.x_signed??'unknown',y:e.y??'unknown',tile:e.tile_9bit??'unknown',palette:e.palette??'unknown',priority:e.priority??'unknown',large:e.large??'unknown',dimensions:[e.noninterlaced_width??'unknown',e.noninterlaced_height??'unknown'],unknown:e.unknown},null,2);const table=document.createElement('table');e.bytes.forEach(b=>{let row=document.createElement('tr');const link=b.dma_provenance,w=link?.writer;const chain=link?'writer '+(w?(w.actor??'unknown actor')+' PC '+(w.pc===undefined?'unknown':'$'+w.pc.toString(16))+' event '+w.id:'unknown')+' → DMA '+link.channel+' read '+link.read.id+' → $2104 '+link.register_write.id+' → OAM '+link.oam_write.id:'origin unknown';[ 'OAM '+b.address, 'mask $'+b.used_mask.toString(16), b.value??'unknown', b.status,chain].forEach(v=>{let cell=document.createElement('td');cell.textContent=v;row.append(cell)});table.append(row)});$('spriteevents').replaceChildren(table);$('spriteraw').textContent=JSON.stringify(e.bytes,null,2);updateSprite();} $('sprites').onchange=showSprite;showSprite();}else{$('sprites').disabled=true;$('spritefields').textContent='Provenance capture unavailable';}
if(m.frames){m.frames.records.forEach(f=>{let n=document.createElement('option');n.value=f.index;n.textContent='Original PPU frame '+f.number;$('frames').append(n)});function frame(){const f=m.frames.records.find(f=>String(f.index)===$('frames').value);if(!f)return;$('picture').src='/api/frame?index='+f.index;$('picture').hidden=false;$('frameidentity').textContent='Host '+f.trace_frame+' / PPU '+f.number+' · PNG '+f.png_sha256+' · original interpreter; no association with selected OAM entry';}$('frames').onchange=frame;frame();}else{$('frames').disabled=true;}
if(m.experiment_enabled){$('execute').disabled=false;$('restore').disabled=false;$('jobstatus').textContent='Ready: source increment edit; original C baseline must match before edited results are shown.';
let running=false;
async function poll(id){const r=await fetch('/api/job?id='+encodeURIComponent(id));if(!r.ok)throw Error('Job unavailable');const j=await r.json();$('jobstatus').textContent=j.status+(j.error?': '+j.error:'');if(j.status==='running'){setTimeout(()=>poll(id).catch(fail),1000);return;}running=false;$('execute').disabled=$('object').value==='oam';$('restore').disabled=$('object').value==='oam';if(j.status!=='complete')return;$('jobidentity').textContent=JSON.stringify({job:j.id,config:j.config_sha256,addend:j.addend,baseline_agreement:j.baseline_agreement,captured_proof_eligible:j.captured_proof_eligible,frame_differences:j.frame_differences,original_compiler:j.original.compiled,edited_compiler:j.edited.compiled,scope:'Timed bounded template; not generic decomp proof'},null,2);const frames=$('jobframes');frames.innerHTML='';j.edited.replica.frames.forEach((f,i)=>{let n=document.createElement('option');n.value=i;n.textContent='PPU '+f.ppu_frame+' / relative '+f.relative_frame;frames.append(n)});frames.disabled=false;const first=j.edited.replica.frames.findIndex((f,i)=>f.framebuffer_sha256!==j.original.replica.frames[i].framebuffer_sha256);frames.value=String(first<0?0:first);function show(){let i=frames.value;$('before').src='/api/job/frame?id='+encodeURIComponent(id)+'&branch=original&index='+i;$('after').src='/api/job/frame?id='+encodeURIComponent(id)+'&branch=edited&index='+i;$('before').hidden=false;$('after').hidden=false;const a=j.original.replica.frames[Number(i)],b=j.edited.replica.frames[Number(i)];$('jobframeidentity').textContent='Original PPU '+a.ppu_frame+' / edited PPU '+b.ppu_frame+' · pixels '+(a.framebuffer_sha256===b.framebuffer_sha256?'equal':'different')+' · source increment '+j.addend+' · captured proof false';}frames.onchange=show;show();}
function fail(e){running=false;$('jobstatus').textContent=e.message;$('execute').disabled=false;$('restore').disabled=false;}
async function execute(addend){if(running||$('object').value!=='polygon')return;running=true;$('execute').disabled=true;$('restore').disabled=true;$('before').hidden=true;$('after').hidden=true;try{const r=await fetch('/api/experiment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({addend})});if(!r.ok)throw Error(await r.text());const j=await r.json();poll(j.id).catch(fail);}catch(e){fail(e)}}
$('execute').onclick=()=>{const n=Number($('increment').value);if(!Number.isInteger(n)||n<1||n>12){$('jobstatus').textContent='Increment must be 1..12';return}execute(n)};$('restore').onclick=()=>{$('increment').value=5;execute(5)};
}
if(m.sprite_experiment_id){
$('spriteJobStatus').textContent='Ready for the operator-selected OAM object only. No-edit baseline must match before data intervention results are shown.';
async function spritePoll(id){const r=await fetch('/api/sprite-job?id='+encodeURIComponent(id));if(!r.ok)throw Error('Sprite job unavailable');const j=await r.json();$('spriteJobStatus').textContent=j.status+(j.error?': '+j.error:'');if(j.status==='running'){setTimeout(()=>spritePoll(id).catch(spriteFail),1000);return}spriteRunning=false;updateSprite();if(j.status!=='complete')return;
$('jobidentity').textContent=JSON.stringify({job:j.id,kind:j.kind,selected_sprite:j.sprite_id,large:j.large,config:j.config_sha256,baseline_agreement:j.baseline_agreement,captured_proof_eligible:false,replacement_executed:false,frame_differences:j.frame_differences,observed:j.edited.sprite_experiment,scope:'Experimental WRAM size bit; pixel ownership remains unknown'},null,2);
const frames=$('jobframes');frames.innerHTML='';j.edited.replica.frames.forEach((f,i)=>{let n=document.createElement('option');n.value=i;n.textContent='PPU '+f.ppu_frame+' / relative '+i;frames.append(n)});frames.disabled=false;let first=j.edited.replica.frames.findIndex((f,i)=>f.framebuffer_sha256!==j.original.replica.frames[i].framebuffer_sha256);frames.value=String(first<0?0:first);function show(){let i=Number(frames.value);$('before').src='/api/sprite-job/frame?id='+encodeURIComponent(id)+'&branch=original&index='+i;$('after').src='/api/sprite-job/frame?id='+encodeURIComponent(id)+'&branch=edited&index='+i;$('before').hidden=false;$('after').hidden=false;const a=j.original.replica.frames[i],b=j.edited.replica.frames[i];$('jobframeidentity').textContent='Original interpreter PPU '+a.ppu_frame+' / experimental data PPU '+b.ppu_frame+' · pixels '+(a.framebuffer_sha256===b.framebuffer_sha256?'equal':'different')+' · OAM '+j.edited.sprite_experiment.captured_explanation.sprite+' · captured proof false; pixel ownership unknown';}frames.onchange=show;show();}
function spriteFail(e){spriteRunning=false;updateSprite();$('spriteJobStatus').textContent=e.message;}
async function spriteExecute(large){if(spriteRunning||objects.value!=='oam'||$('sprites').value!==m.sprite_experiment_id)return;spriteRunning=true;updateSprite();$('before').hidden=true;$('after').hidden=true;try{const r=await fetch('/api/sprite-experiment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sprite_id:$('sprites').value,large})});if(!r.ok)throw Error(await r.text());const j=await r.json();spritePoll(j.id).catch(spriteFail);}catch(e){spriteFail(e)}}
$('spriteExecute').onclick=()=>spriteExecute($('spriteLarge').value==='true');$('spriteReset').onclick=()=>{const e=m.sprites.entries.find(e=>e.id===m.sprite_experiment_id);if(typeof e?.explanation.large!=='boolean'){spriteFail(Error('Captured size unavailable'));return}$('spriteLarge').value=String(e.explanation.large);spriteExecute(e.explanation.large)};
updateSprite();}
$('baseline').textContent=m.baseline;$('frame').textContent=m.frames?'Separate original interpreter capture; experiment frames are shown below.':m.frame;$('sprite').textContent=m.sprite_provenance;$('pins').textContent=JSON.stringify(o.artifacts,null,2);
}).catch(e=>document.getElementById('error').textContent=e.message);
</script>`
