package web

const page = `<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>SNES rotation editor</title>
<style>body{font:16px system-ui;background:#171c23;color:#e8edf2;margin:0}header,main{padding:24px;max-width:1100px;margin:auto}main{display:grid;grid-template-columns:1fr 1fr;gap:20px}section{background:#222b36;padding:20px;border-radius:8px}h1{margin:0}small{color:#adb9c6}button,select,input{font:inherit;padding:8px;background:#e8edf2;color:#17202a;border:0;border-radius:4px}pre{white-space:pre-wrap;overflow-wrap:anywhere}.tag{color:#9ad6c3}#error{color:#ffbdab}@media(max-width:700px){main{display:block}section{margin-bottom:16px}}</style>
<header><h1>Intro rotation</h1><p>Original observations · reversible draft · experiment evidence</p><small id="identity"></small><p id="error"></p></header>
<main><section><h2>Selected object</h2><select id="object"><option value="polygon">Polygon rotation</option><option value="oam">OAM sprite entry</option></select><div id="polygon"><h3>Selected field</h3><select id="fields"></select><pre id="selection"></pre><h3>Observed</h3><p id="observed"></p><h3>Advisory interpretation</h3><p id="inferred"></p></div><div id="oam" hidden><select id="sprites"></select><pre id="spritefields"></pre><h3>Exact observed byte versions</h3><pre id="spriteevents"></pre><p>Low-table latch origins may be unknown. OAM entry interpretation is not visible pixel ownership.</p></div></section>
<section><h2>Parameter draft</h2><label>Initial angular phase <input id="draft" type="number"></label><p id="draftstate">No draft</p><button id="reset">Discard draft</button><p>Draft only. Changing this control does not execute C or alter the original capture.</p><h3>Original baseline</h3><p id="baseline"></p><h3>Experiment</h3><p>Not executed. No experimental result or proof eligibility.</p></section>
<section><h2>Frame</h2><p id="frame"></p><select id="frames"></select><p id="frameidentity"></p><img id="picture" style="max-width:100%;image-rendering:pixelated" hidden alt="Original interpreter capture"><h3>Sprite explanation</h3><p id="sprite"></p></section><section><h2>Evidence pins</h2><pre id="pins"></pre><p>Hashes bind retained bytes; they do not establish admission, timing, or pixel ownership.</p></section></main>
<script>
fetch('/api/target').then(r=>{if(!r.ok)throw Error('Target unavailable');return r.json()}).then(m=>{
const t=m.target,o=m.observation,$=id=>document.getElementById(id);
$('identity').textContent=t.id+' · manifest '+m.manifest_sha256;
const fields=[t.parameter.field,...t.effects];fields.forEach((f,i)=>{let n=document.createElement('option');n.value=i;n.textContent=f.name;$('fields').append(n)});
function select(){let f=fields[Number($('fields').value)];$('selection').textContent='WRAM $'+f.address.toString(16).toUpperCase()+' · '+f.bytes+' byte(s)';const edit=$('draft');edit.disabled=Number($('fields').value)!==0||$('object').value==='oam';edit.value='';$('draftstate').textContent=edit.disabled?'Draft unavailable for selected field':'No draft';}select();$('fields').onchange=select;
$('observed').textContent=o.handler_entries+' original intervals, frames '+o.observed_frames.join('–')+', '+o.contiguous_instructions_per_handler+' instructions and '+o.ordered_wram_writes_per_handler+' writes each. '+o.observed_scope;
$('inferred').textContent=t.advisory_crosswalk+' · Names and parameter meaning are advisory.';
const d=$('draft');d.min=t.parameter.minimum;d.max=t.parameter.maximum;
d.oninput=()=>{$('draftstate').textContent=d.value===''?'No draft':d.validity.valid?'Unexecuted draft: '+d.value:'Outside descriptor range';};$('reset').onclick=()=>{d.value='';d.oninput()};
const objects=$('object'),oam=$('oam');
function object(){let sprite=objects.value==='oam';$('polygon').hidden=sprite;oam.hidden=!sprite;d.disabled=sprite;$('draftstate').textContent=sprite?'Parameter drafting unavailable for OAM selection':'No draft';d.value='';select();}objects.onchange=object;
if(m.sprites){m.sprites.entries.forEach(e=>{let n=document.createElement('option');n.value=e.id;n.textContent='OAM '+e.explanation.sprite;$('sprites').append(n)});function showSprite(){let x=m.sprites.entries.find(e=>e.id===$('sprites').value);if(!x)return;const e=x.explanation;$('spritefields').textContent=JSON.stringify({stable_id:x.id,capture:m.sprites.capture_sha256,host_frame:e.through_host_frame,x:e.x_signed??'unknown',y:e.y??'unknown',tile:e.tile_9bit??'unknown',palette:e.palette??'unknown',priority:e.priority??'unknown',dimensions:[e.noninterlaced_width??'unknown',e.noninterlaced_height??'unknown'],unknown:e.unknown},null,2);$('spriteevents').textContent=JSON.stringify(e.bytes,null,2);} $('sprites').onchange=showSprite;showSprite();}else{$('sprites').disabled=true;$('spritefields').textContent='Provenance capture unavailable';}
if(m.frames){m.frames.records.forEach(f=>{let n=document.createElement('option');n.value=f.index;n.textContent='Original PPU frame '+f.number;$('frames').append(n)});function frame(){const f=m.frames.records.find(f=>String(f.index)===$('frames').value);if(!f)return;$('picture').src='/api/frame?index='+f.index;$('picture').hidden=false;$('frameidentity').textContent='Host '+f.trace_frame+' / PPU '+f.number+' · PNG '+f.png_sha256+' · original interpreter; no association with selected OAM entry';}$('frames').onchange=frame;frame();}else{$('frames').disabled=true;}
$('baseline').textContent=m.baseline;$('frame').textContent=m.frame;$('sprite').textContent=m.sprite_provenance;$('pins').textContent=JSON.stringify(o.artifacts,null,2);
}).catch(e=>document.getElementById('error').textContent=e.message);
</script>`
