// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: snes/live/v1/live.proto

package sneslivev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SNESLiveService_LoadROM_FullMethodName           = "/snes.live.v1.SNESLiveService/LoadROM"
	SNESLiveService_LoadState_FullMethodName         = "/snes.live.v1.SNESLiveService/LoadState"
	SNESLiveService_Reset_FullMethodName             = "/snes.live.v1.SNESLiveService/Reset"
	SNESLiveService_SetInput_FullMethodName          = "/snes.live.v1.SNESLiveService/SetInput"
	SNESLiveService_Step_FullMethodName              = "/snes.live.v1.SNESLiveService/Step"
	SNESLiveService_Run_FullMethodName               = "/snes.live.v1.SNESLiveService/Run"
	SNESLiveService_RunStream_FullMethodName         = "/snes.live.v1.SNESLiveService/RunStream"
	SNESLiveService_ReadWatches_FullMethodName       = "/snes.live.v1.SNESLiveService/ReadWatches"
	SNESLiveService_ReadMemory_FullMethodName        = "/snes.live.v1.SNESLiveService/ReadMemory"
	SNESLiveService_Snapshot_FullMethodName          = "/snes.live.v1.SNESLiveService/Snapshot"
	SNESLiveService_Restore_FullMethodName           = "/snes.live.v1.SNESLiveService/Restore"
	SNESLiveService_Fork_FullMethodName              = "/snes.live.v1.SNESLiveService/Fork"
	SNESLiveService_RunFromCheckpoint_FullMethodName = "/snes.live.v1.SNESLiveService/RunFromCheckpoint"
)

// SNESLiveServiceClient is the client API for SNESLiveService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SNESLiveServiceClient interface {
	LoadROM(ctx context.Context, in *LoadROMRequest, opts ...grpc.CallOption) (*LoadROMResponse, error)
	LoadState(ctx context.Context, in *LoadStateRequest, opts ...grpc.CallOption) (*LoadStateResponse, error)
	Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetResponse, error)
	SetInput(ctx context.Context, in *SetInputRequest, opts ...grpc.CallOption) (*SetInputResponse, error)
	Step(ctx context.Context, in *StepRequest, opts ...grpc.CallOption) (*StepResponse, error)
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error)
	RunStream(ctx context.Context, in *RunStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunStreamResponse], error)
	ReadWatches(ctx context.Context, in *ReadWatchesRequest, opts ...grpc.CallOption) (*ReadWatchesResponse, error)
	ReadMemory(ctx context.Context, in *ReadMemoryRequest, opts ...grpc.CallOption) (*ReadMemoryResponse, error)
	Snapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error)
	Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error)
	Fork(ctx context.Context, in *ForkRequest, opts ...grpc.CallOption) (*ForkResponse, error)
	RunFromCheckpoint(ctx context.Context, in *RunFromCheckpointRequest, opts ...grpc.CallOption) (*RunFromCheckpointResponse, error)
}

type sNESLiveServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSNESLiveServiceClient(cc grpc.ClientConnInterface) SNESLiveServiceClient {
	return &sNESLiveServiceClient{cc}
}

func (c *sNESLiveServiceClient) LoadROM(ctx context.Context, in *LoadROMRequest, opts ...grpc.CallOption) (*LoadROMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadROMResponse)
	err := c.cc.Invoke(ctx, SNESLiveService_LoadROM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sNESLiveServiceClient) LoadState(ctx context.Context, in *LoadStateRequest, opts ...grpc.CallOption) (*LoadStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadStateResponse)
	err := c.cc.Invoke(ctx, SNESLiveService_LoadState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sNESLiveServiceClient) Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetResponse)
	err := c.cc.Invoke(ctx, SNESLiveService_Reset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sNESLiveServiceClient) SetInput(ctx context.Context, in *SetInputRequest, opts ...grpc.CallOption) (*SetInputResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetInputResponse)
	err := c.cc.Invoke(ctx, SNESLiveService_SetInput_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sNESLiveServiceClient) Step(ctx context.Context, in *StepRequest, opts ...grpc.CallOption) (*StepResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StepResponse)
	err := c.cc.Invoke(ctx, SNESLiveService_Step_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sNESLiveServiceClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunResponse)
	err := c.cc.Invoke(ctx, SNESLiveService_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sNESLiveServiceClient) RunStream(ctx context.Context, in *RunStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SNESLiveService_ServiceDesc.Streams[0], SNESLiveService_RunStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunStreamRequest, RunStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SNESLiveService_RunStreamClient = grpc.ServerStreamingClient[RunStreamResponse]

func (c *sNESLiveServiceClient) ReadWatches(ctx context.Context, in *ReadWatchesRequest, opts ...grpc.CallOption) (*ReadWatchesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadWatchesResponse)
	err := c.cc.Invoke(ctx, SNESLiveService_ReadWatches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sNESLiveServiceClient) ReadMemory(ctx context.Context, in *ReadMemoryRequest, opts ...grpc.CallOption) (*ReadMemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadMemoryResponse)
	err := c.cc.Invoke(ctx, SNESLiveService_ReadMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sNESLiveServiceClient) Snapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotResponse)
	err := c.cc.Invoke(ctx, SNESLiveService_Snapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sNESLiveServiceClient) Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreResponse)
	err := c.cc.Invoke(ctx, SNESLiveService_Restore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sNESLiveServiceClient) Fork(ctx context.Context, in *ForkRequest, opts ...grpc.CallOption) (*ForkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForkResponse)
	err := c.cc.Invoke(ctx, SNESLiveService_Fork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sNESLiveServiceClient) RunFromCheckpoint(ctx context.Context, in *RunFromCheckpointRequest, opts ...grpc.CallOption) (*RunFromCheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunFromCheckpointResponse)
	err := c.cc.Invoke(ctx, SNESLiveService_RunFromCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SNESLiveServiceServer is the server API for SNESLiveService service.
// All implementations must embed UnimplementedSNESLiveServiceServer
// for forward compatibility.
type SNESLiveServiceServer interface {
	LoadROM(context.Context, *LoadROMRequest) (*LoadROMResponse, error)
	LoadState(context.Context, *LoadStateRequest) (*LoadStateResponse, error)
	Reset(context.Context, *ResetRequest) (*ResetResponse, error)
	SetInput(context.Context, *SetInputRequest) (*SetInputResponse, error)
	Step(context.Context, *StepRequest) (*StepResponse, error)
	Run(context.Context, *RunRequest) (*RunResponse, error)
	RunStream(*RunStreamRequest, grpc.ServerStreamingServer[RunStreamResponse]) error
	ReadWatches(context.Context, *ReadWatchesRequest) (*ReadWatchesResponse, error)
	ReadMemory(context.Context, *ReadMemoryRequest) (*ReadMemoryResponse, error)
	Snapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error)
	Restore(context.Context, *RestoreRequest) (*RestoreResponse, error)
	Fork(context.Context, *ForkRequest) (*ForkResponse, error)
	RunFromCheckpoint(context.Context, *RunFromCheckpointRequest) (*RunFromCheckpointResponse, error)
	mustEmbedUnimplementedSNESLiveServiceServer()
}

// UnimplementedSNESLiveServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSNESLiveServiceServer struct{}

func (UnimplementedSNESLiveServiceServer) LoadROM(context.Context, *LoadROMRequest) (*LoadROMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadROM not implemented")
}
func (UnimplementedSNESLiveServiceServer) LoadState(context.Context, *LoadStateRequest) (*LoadStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadState not implemented")
}
func (UnimplementedSNESLiveServiceServer) Reset(context.Context, *ResetRequest) (*ResetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reset not implemented")
}
func (UnimplementedSNESLiveServiceServer) SetInput(context.Context, *SetInputRequest) (*SetInputResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetInput not implemented")
}
func (UnimplementedSNESLiveServiceServer) Step(context.Context, *StepRequest) (*StepResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Step not implemented")
}
func (UnimplementedSNESLiveServiceServer) Run(context.Context, *RunRequest) (*RunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedSNESLiveServiceServer) RunStream(*RunStreamRequest, grpc.ServerStreamingServer[RunStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method RunStream not implemented")
}
func (UnimplementedSNESLiveServiceServer) ReadWatches(context.Context, *ReadWatchesRequest) (*ReadWatchesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadWatches not implemented")
}
func (UnimplementedSNESLiveServiceServer) ReadMemory(context.Context, *ReadMemoryRequest) (*ReadMemoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadMemory not implemented")
}
func (UnimplementedSNESLiveServiceServer) Snapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Snapshot not implemented")
}
func (UnimplementedSNESLiveServiceServer) Restore(context.Context, *RestoreRequest) (*RestoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Restore not implemented")
}
func (UnimplementedSNESLiveServiceServer) Fork(context.Context, *ForkRequest) (*ForkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Fork not implemented")
}
func (UnimplementedSNESLiveServiceServer) RunFromCheckpoint(context.Context, *RunFromCheckpointRequest) (*RunFromCheckpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunFromCheckpoint not implemented")
}
func (UnimplementedSNESLiveServiceServer) mustEmbedUnimplementedSNESLiveServiceServer() {}
func (UnimplementedSNESLiveServiceServer) testEmbeddedByValue()                         {}

// UnsafeSNESLiveServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SNESLiveServiceServer will
// result in compilation errors.
type UnsafeSNESLiveServiceServer interface {
	mustEmbedUnimplementedSNESLiveServiceServer()
}

func RegisterSNESLiveServiceServer(s grpc.ServiceRegistrar, srv SNESLiveServiceServer) {
	// If the following call panics, it indicates UnimplementedSNESLiveServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SNESLiveService_ServiceDesc, srv)
}

func _SNESLiveService_LoadROM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadROMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SNESLiveServiceServer).LoadROM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SNESLiveService_LoadROM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SNESLiveServiceServer).LoadROM(ctx, req.(*LoadROMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SNESLiveService_LoadState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SNESLiveServiceServer).LoadState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SNESLiveService_LoadState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SNESLiveServiceServer).LoadState(ctx, req.(*LoadStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SNESLiveService_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SNESLiveServiceServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SNESLiveService_Reset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SNESLiveServiceServer).Reset(ctx, req.(*ResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SNESLiveService_SetInput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetInputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SNESLiveServiceServer).SetInput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SNESLiveService_SetInput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SNESLiveServiceServer).SetInput(ctx, req.(*SetInputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SNESLiveService_Step_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SNESLiveServiceServer).Step(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SNESLiveService_Step_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SNESLiveServiceServer).Step(ctx, req.(*StepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SNESLiveService_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SNESLiveServiceServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SNESLiveService_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SNESLiveServiceServer).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SNESLiveService_RunStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SNESLiveServiceServer).RunStream(m, &grpc.GenericServerStream[RunStreamRequest, RunStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SNESLiveService_RunStreamServer = grpc.ServerStreamingServer[RunStreamResponse]

func _SNESLiveService_ReadWatches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadWatchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SNESLiveServiceServer).ReadWatches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SNESLiveService_ReadWatches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SNESLiveServiceServer).ReadWatches(ctx, req.(*ReadWatchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SNESLiveService_ReadMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SNESLiveServiceServer).ReadMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SNESLiveService_ReadMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SNESLiveServiceServer).ReadMemory(ctx, req.(*ReadMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SNESLiveService_Snapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SNESLiveServiceServer).Snapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SNESLiveService_Snapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SNESLiveServiceServer).Snapshot(ctx, req.(*SnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SNESLiveService_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SNESLiveServiceServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SNESLiveService_Restore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SNESLiveServiceServer).Restore(ctx, req.(*RestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SNESLiveService_Fork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SNESLiveServiceServer).Fork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SNESLiveService_Fork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SNESLiveServiceServer).Fork(ctx, req.(*ForkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SNESLiveService_RunFromCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunFromCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SNESLiveServiceServer).RunFromCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SNESLiveService_RunFromCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SNESLiveServiceServer).RunFromCheckpoint(ctx, req.(*RunFromCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SNESLiveService_ServiceDesc is the grpc.ServiceDesc for SNESLiveService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SNESLiveService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "snes.live.v1.SNESLiveService",
	HandlerType: (*SNESLiveServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoadROM",
			Handler:    _SNESLiveService_LoadROM_Handler,
		},
		{
			MethodName: "LoadState",
			Handler:    _SNESLiveService_LoadState_Handler,
		},
		{
			MethodName: "Reset",
			Handler:    _SNESLiveService_Reset_Handler,
		},
		{
			MethodName: "SetInput",
			Handler:    _SNESLiveService_SetInput_Handler,
		},
		{
			MethodName: "Step",
			Handler:    _SNESLiveService_Step_Handler,
		},
		{
			MethodName: "Run",
			Handler:    _SNESLiveService_Run_Handler,
		},
		{
			MethodName: "ReadWatches",
			Handler:    _SNESLiveService_ReadWatches_Handler,
		},
		{
			MethodName: "ReadMemory",
			Handler:    _SNESLiveService_ReadMemory_Handler,
		},
		{
			MethodName: "Snapshot",
			Handler:    _SNESLiveService_Snapshot_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _SNESLiveService_Restore_Handler,
		},
		{
			MethodName: "Fork",
			Handler:    _SNESLiveService_Fork_Handler,
		},
		{
			MethodName: "RunFromCheckpoint",
			Handler:    _SNESLiveService_RunFromCheckpoint_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunStream",
			Handler:       _SNESLiveService_RunStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "snes/live/v1/live.proto",
}
