// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: snes/live/v1/live.proto

package sneslivev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoadROMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadROMRequest) Reset() {
	*x = LoadROMRequest{}
	mi := &file_snes_live_v1_live_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadROMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadROMRequest) ProtoMessage() {}

func (x *LoadROMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snes_live_v1_live_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadROMRequest.ProtoReflect.Descriptor instead.
func (*LoadROMRequest) Descriptor() ([]byte, []int) {
	return file_snes_live_v1_live_proto_rawDescGZIP(), []int{0}
}

func (x *LoadROMRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type LoadROMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadROMResponse) Reset() {
	*x = LoadROMResponse{}
	mi := &file_snes_live_v1_live_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadROMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadROMResponse) ProtoMessage() {}

func (x *LoadROMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snes_live_v1_live_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadROMResponse.ProtoReflect.Descriptor instead.
func (*LoadROMResponse) Descriptor() ([]byte, []int) {
	return file_snes_live_v1_live_proto_rawDescGZIP(), []int{1}
}

func (x *LoadROMResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type LoadStateRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Path                  string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	AllowStateRomMismatch bool                   `protobuf:"varint,2,opt,name=allow_state_rom_mismatch,json=allowStateRomMismatch,proto3" json:"allow_state_rom_mismatch,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *LoadStateRequest) Reset() {
	*x = LoadStateRequest{}
	mi := &file_snes_live_v1_live_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadStateRequest) ProtoMessage() {}

func (x *LoadStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snes_live_v1_live_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadStateRequest.ProtoReflect.Descriptor instead.
func (*LoadStateRequest) Descriptor() ([]byte, []int) {
	return file_snes_live_v1_live_proto_rawDescGZIP(), []int{2}
}

func (x *LoadStateRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *LoadStateRequest) GetAllowStateRomMismatch() bool {
	if x != nil {
		return x.AllowStateRomMismatch
	}
	return false
}

type LoadStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadStateResponse) Reset() {
	*x = LoadStateResponse{}
	mi := &file_snes_live_v1_live_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadStateResponse) ProtoMessage() {}

func (x *LoadStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snes_live_v1_live_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadStateResponse.ProtoReflect.Descriptor instead.
func (*LoadStateResponse) Descriptor() ([]byte, []int) {
	return file_snes_live_v1_live_proto_rawDescGZIP(), []int{3}
}

func (x *LoadStateResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_snes_live_v1_live_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snes_live_v1_live_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_snes_live_v1_live_proto_rawDescGZIP(), []int{4}
}

type ResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetResponse) Reset() {
	*x = ResetResponse{}
	mi := &file_snes_live_v1_live_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResponse) ProtoMessage() {}

func (x *ResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snes_live_v1_live_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResponse.ProtoReflect.Descriptor instead.
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return file_snes_live_v1_live_proto_rawDescGZIP(), []int{5}
}

func (x *ResetResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type SetInputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         uint32                 `protobuf:"varint,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetInputRequest) Reset() {
	*x = SetInputRequest{}
	mi := &file_snes_live_v1_live_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInputRequest) ProtoMessage() {}

func (x *SetInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snes_live_v1_live_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInputRequest.ProtoReflect.Descriptor instead.
func (*SetInputRequest) Descriptor() ([]byte, []int) {
	return file_snes_live_v1_live_proto_rawDescGZIP(), []int{6}
}

func (x *SetInputRequest) GetInput() uint32 {
	if x != nil {
		return x.Input
	}
	return 0
}

type SetInputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetInputResponse) Reset() {
	*x = SetInputResponse{}
	mi := &file_snes_live_v1_live_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetInputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInputResponse) ProtoMessage() {}

func (x *SetInputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snes_live_v1_live_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInputResponse.ProtoReflect.Descriptor instead.
func (*SetInputResponse) Descriptor() ([]byte, []int) {
	return file_snes_live_v1_live_proto_rawDescGZIP(), []int{7}
}

func (x *SetInputResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type StepRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frames        uint32                 `protobuf:"varint,1,opt,name=frames,proto3" json:"frames,omitempty"`
	Input         uint32                 `protobuf:"varint,2,opt,name=input,proto3" json:"input,omitempty"`
	WatchSpec     *WatchSpec             `protobuf:"bytes,3,opt,name=watch_spec,json=watchSpec,proto3" json:"watch_spec,omitempty"`
	Framebuffer   string                 `protobuf:"bytes,4,opt,name=framebuffer,proto3" json:"framebuffer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepRequest) Reset() {
	*x = StepRequest{}
	mi := &file_snes_live_v1_live_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepRequest) ProtoMessage() {}

func (x *StepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snes_live_v1_live_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepRequest.ProtoReflect.Descriptor instead.
func (*StepRequest) Descriptor() ([]byte, []int) {
	return file_snes_live_v1_live_proto_rawDescGZIP(), []int{8}
}

func (x *StepRequest) GetFrames() uint32 {
	if x != nil {
		return x.Frames
	}
	return 0
}

func (x *StepRequest) GetInput() uint32 {
	if x != nil {
		return x.Input
	}
	return 0
}

func (x *StepRequest) GetWatchSpec() *WatchSpec {
	if x != nil {
		return x.WatchSpec
	}
	return nil
}

func (x *StepRequest) GetFramebuffer() string {
	if x != nil {
		return x.Framebuffer
	}
	return ""
}

type StepResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Frames          uint32                 `protobuf:"varint,1,opt,name=frames,proto3" json:"frames,omitempty"`
	Input           uint32                 `protobuf:"varint,2,opt,name=input,proto3" json:"input,omitempty"`
	Watches         map[string]uint64      `protobuf:"bytes,3,rep,name=watches,proto3" json:"watches,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	FramebufferHash string                 `protobuf:"bytes,4,opt,name=framebuffer_hash,json=framebufferHash,proto3" json:"framebuffer_hash,omitempty"`
	FrameRgba       []byte                 `protobuf:"bytes,5,opt,name=frame_rgba,json=frameRgba,proto3" json:"frame_rgba,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StepResponse) Reset() {
	*x = StepResponse{}
	mi := &file_snes_live_v1_live_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepResponse) ProtoMessage() {}

func (x *StepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snes_live_v1_live_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepResponse.ProtoReflect.Descriptor instead.
func (*StepResponse) Descriptor() ([]byte, []int) {
	return file_snes_live_v1_live_proto_rawDescGZIP(), []int{9}
}

func (x *StepResponse) GetFrames() uint32 {
	if x != nil {
		return x.Frames
	}
	return 0
}

func (x *StepResponse) GetInput() uint32 {
	if x != nil {
		return x.Input
	}
	return 0
}

func (x *StepResponse) GetWatches() map[string]uint64 {
	if x != nil {
		return x.Watches
	}
	return nil
}

func (x *StepResponse) GetFramebufferHash() string {
	if x != nil {
		return x.FramebufferHash
	}
	return ""
}

func (x *StepResponse) GetFrameRgba() []byte {
	if x != nil {
		return x.FrameRgba
	}
	return nil
}

type RunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frames        uint32                 `protobuf:"varint,1,opt,name=frames,proto3" json:"frames,omitempty"`
	Input         *uint32                `protobuf:"varint,2,opt,name=input,proto3,oneof" json:"input,omitempty"`
	InputSequence []uint32               `protobuf:"varint,3,rep,packed,name=input_sequence,json=inputSequence,proto3" json:"input_sequence,omitempty"`
	WatchSpec     *WatchSpec             `protobuf:"bytes,4,opt,name=watch_spec,json=watchSpec,proto3" json:"watch_spec,omitempty"`
	EventFilter   []string               `protobuf:"bytes,5,rep,name=event_filter,json=eventFilter,proto3" json:"event_filter,omitempty"`
	Framebuffer   string                 `protobuf:"bytes,6,opt,name=framebuffer,proto3" json:"framebuffer,omitempty"`
	Every         uint32                 `protobuf:"varint,7,opt,name=every,proto3" json:"every,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_snes_live_v1_live_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snes_live_v1_live_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_snes_live_v1_live_proto_rawDescGZIP(), []int{10}
}

func (x *RunRequest) GetFrames() uint32 {
	if x != nil {
		return x.Frames
	}
	return 0
}

func (x *RunRequest) GetInput() uint32 {
	if x != nil && x.Input != nil {
		return *x.Input
	}
	return 0
}

func (x *RunRequest) GetInputSequence() []uint32 {
	if x != nil {
		return x.InputSequence
	}
	return nil
}

func (x *RunRequest) GetWatchSpec() *WatchSpec {
	if x != nil {
		return x.WatchSpec
	}
	return nil
}

func (x *RunRequest) GetEventFilter() []string {
	if x != nil {
		return x.EventFilter
	}
	return nil
}

func (x *RunRequest) GetFramebuffer() string {
	if x != nil {
		return x.Framebuffer
	}
	return ""
}

func (x *RunRequest) GetEvery() uint32 {
	if x != nil {
		return x.Every
	}
	return 0
}

type RunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *RunResult             `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_snes_live_v1_live_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snes_live_v1_live_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_snes_live_v1_live_proto_rawDescGZIP(), []int{11}
}

func (x *RunResponse) GetResult() *RunResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type RunResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Frames          uint32                 `protobuf:"varint,1,opt,name=frames,proto3" json:"frames,omitempty"`
	InputHash       string                 `protobuf:"bytes,2,opt,name=input_hash,json=inputHash,proto3" json:"input_hash,omitempty"`
	EventFilter     []string               `protobuf:"bytes,3,rep,name=event_filter,json=eventFilter,proto3" json:"event_filter,omitempty"`
	Watches         map[string]uint64      `protobuf:"bytes,4,rep,name=watches,proto3" json:"watches,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	FramebufferHash string                 `protobuf:"bytes,5,opt,name=framebuffer_hash,json=framebufferHash,proto3" json:"framebuffer_hash,omitempty"`
	ComponentHashes map[string]string      `protobuf:"bytes,6,rep,name=component_hashes,json=componentHashes,proto3" json:"component_hashes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FinalStateHash  string                 `protobuf:"bytes,7,opt,name=final_state_hash,json=finalStateHash,proto3" json:"final_state_hash,omitempty"`
	FrameRgba       []byte                 `protobuf:"bytes,8,opt,name=frame_rgba,json=frameRgba,proto3" json:"frame_rgba,omitempty"`
	FrameSummaries  []*FrameSummary        `protobuf:"bytes,9,rep,name=frame_summaries,json=frameSummaries,proto3" json:"frame_summaries,omitempty"`
	Checkpoint      string                 `protobuf:"bytes,10,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RunResult) Reset() {
	*x = RunResult{}
	mi := &file_snes_live_v1_live_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResult) ProtoMessage() {}

func (x *RunResult) ProtoReflect() protoreflect.Message {
	mi := &file_snes_live_v1_live_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResult.ProtoReflect.Descriptor instead.
func (*RunResult) Descriptor() ([]byte, []int) {
	return file_snes_live_v1_live_proto_rawDescGZIP(), []int{12}
}

func (x *RunResult) GetFrames() uint32 {
	if x != nil {
		return x.Frames
	}
	return 0
}

func (x *RunResult) GetInputHash() string {
	if x != nil {
		return x.InputHash
	}
	return ""
}

func (x *RunResult) GetEventFilter() []string {
	if x != nil {
		return x.EventFilter
	}
	return nil
}

func (x *RunResult) GetWatches() map[string]uint64 {
	if x != nil {
		return x.Watches
	}
	return nil
}

func (x *RunResult) GetFramebufferHash() string {
	if x != nil {
		return x.FramebufferHash
	}
	return ""
}

func (x *RunResult) GetComponentHashes() map[string]string {
	if x != nil {
		return x.ComponentHashes
	}
	return nil
}

func (x *RunResult) GetFinalStateHash() string {
	if x != nil {
		return x.FinalStateHash
	}
	return ""
}

func (x *RunResult) GetFrameRgba() []byte {
	if x != nil {
		return x.FrameRgba
	}
	return nil
}

func (x *RunResult) GetFrameSummaries() []*FrameSummary {
	if x != nil {
		return x.FrameSummaries
	}
	return nil
}

func (x *RunResult) GetCheckpoint() string {
	if x != nil {
		return x.Checkpoint
	}
	return ""
}

type RunStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *RunRequest            `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunStreamRequest) Reset() {
	*x = RunStreamRequest{}
	mi := &file_snes_live_v1_live_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunStreamRequest) ProtoMessage() {}

func (x *RunStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snes_live_v1_live_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunStreamRequest.ProtoReflect.Descriptor instead.
func (*RunStreamRequest) Descriptor() ([]byte, []int) {
	return file_snes_live_v1_live_proto_rawDescGZIP(), []int{13}
}

func (x *RunStreamRequest) GetRun() *RunRequest {
	if x != nil {
		return x.Run
	}
	return nil
}

type RunFromCheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checkpoint    string                 `protobuf:"bytes,1,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	InputSequence []uint32               `protobuf:"varint,2,rep,packed,name=input_sequence,json=inputSequence,proto3" json:"input_sequence,omitempty"`
	WatchSpec     *WatchSpec             `protobuf:"bytes,3,opt,name=watch_spec,json=watchSpec,proto3" json:"watch_spec,omitempty"`
	EventFilter   []string               `protobuf:"bytes,4,rep,name=event_filter,json=eventFilter,proto3" json:"event_filter,omitempty"`
	Framebuffer   string                 `protobuf:"bytes,5,opt,name=framebuffer,proto3" json:"framebuffer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunFromCheckpointRequest) Reset() {
	*x = RunFromCheckpointRequest{}
	mi := &file_snes_live_v1_live_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunFromCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunFromCheckpointRequest) ProtoMessage() {}

func (x *RunFromCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snes_live_v1_live_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunFromCheckpointRequest.ProtoReflect.Descriptor instead.
func (*RunFromCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_snes_live_v1_live_proto_rawDescGZIP(), []int{14}
}

func (x *RunFromCheckpointRequest) GetCheckpoint() string {
	if x != nil {
		return x.Checkpoint
	}
	return ""
}

func (x *RunFromCheckpointRequest) GetInputSequence() []uint32 {
	if x != nil {
		return x.InputSequence
	}
	return nil
}

func (x *RunFromCheckpointRequest) GetWatchSpec() *WatchSpec {
	if x != nil {
		return x.WatchSpec
	}
	return nil
}

func (x *RunFromCheckpointRequest) GetEventFilter() []string {
	if x != nil {
		return x.EventFilter
	}
	return nil
}

func (x *RunFromCheckpointRequest) GetFramebuffer() string {
	if x != nil {
		return x.Framebuffer
	}
	return ""
}

type RunFromCheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *RunResult             `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunFromCheckpointResponse) Reset() {
	*x = RunFromCheckpointResponse{}
	mi := &file_snes_live_v1_live_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunFromCheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunFromCheckpointResponse) ProtoMessage() {}

func (x *RunFromCheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snes_live_v1_live_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunFromCheckpointResponse.ProtoReflect.Descriptor instead.
func (*RunFromCheckpointResponse) Descriptor() ([]byte, []int) {
	return file_snes_live_v1_live_proto_rawDescGZIP(), []int{15}
}

func (x *RunFromCheckpointResponse) GetResult() *RunResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type RunStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*RunStreamResponse_Frame
	//	*RunStreamResponse_Final
	Event         isRunStreamResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunStreamResponse) Reset() {
	*x = RunStreamResponse{}
	mi := &file_snes_live_v1_live_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunStreamResponse) ProtoMessage() {}

func (x *RunStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snes_live_v1_live_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunStreamResponse.ProtoReflect.Descriptor instead.
func (*RunStreamResponse) Descriptor() ([]byte, []int) {
	return file_snes_live_v1_live_proto_rawDescGZIP(), []int{16}
}

func (x *RunStreamResponse) GetEvent() isRunStreamResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *RunStreamResponse) GetFrame() *FrameSummary {
	if x != nil {
		if x, ok := x.Event.(*RunStreamResponse_Frame); ok {
			return x.Frame
		}
	}
	return nil
}

func (x *RunStreamResponse) GetFinal() *RunResult {
	if x != nil {
		if x, ok := x.Event.(*RunStreamResponse_Final); ok {
			return x.Final
		}
	}
	return nil
}

type isRunStreamResponse_Event interface {
	isRunStreamResponse_Event()
}

type RunStreamResponse_Frame struct {
	Frame *FrameSummary `protobuf:"bytes,1,opt,name=frame,proto3,oneof"`
}

type RunStreamResponse_Final struct {
	Final *RunResult `protobuf:"bytes,2,opt,name=final,proto3,oneof"`
}

func (*RunStreamResponse_Frame) isRunStreamResponse_Event() {}

func (*RunStreamResponse_Final) isRunStreamResponse_Event() {}

type FrameSummary struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Frame           uint32                 `protobuf:"varint,1,opt,name=frame,proto3" json:"frame,omitempty"`
	Input           uint32                 `protobuf:"varint,2,opt,name=input,proto3" json:"input,omitempty"`
	Watches         map[string]uint64      `protobuf:"bytes,3,rep,name=watches,proto3" json:"watches,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	FramebufferHash string                 `protobuf:"bytes,4,opt,name=framebuffer_hash,json=framebufferHash,proto3" json:"framebuffer_hash,omitempty"`
	ComponentHashes map[string]string      `protobuf:"bytes,5,rep,name=component_hashes,json=componentHashes,proto3" json:"component_hashes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FrameSummary) Reset() {
	*x = FrameSummary{}
	mi := &file_snes_live_v1_live_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameSummary) ProtoMessage() {}

func (x *FrameSummary) ProtoReflect() protoreflect.Message {
	mi := &file_snes_live_v1_live_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameSummary.ProtoReflect.Descriptor instead.
func (*FrameSummary) Descriptor() ([]byte, []int) {
	return file_snes_live_v1_live_proto_rawDescGZIP(), []int{17}
}

func (x *FrameSummary) GetFrame() uint32 {
	if x != nil {
		return x.Frame
	}
	return 0
}

func (x *FrameSummary) GetInput() uint32 {
	if x != nil {
		return x.Input
	}
	return 0
}

func (x *FrameSummary) GetWatches() map[string]uint64 {
	if x != nil {
		return x.Watches
	}
	return nil
}

func (x *FrameSummary) GetFramebufferHash() string {
	if x != nil {
		return x.FramebufferHash
	}
	return ""
}

func (x *FrameSummary) GetComponentHashes() map[string]string {
	if x != nil {
		return x.ComponentHashes
	}
	return nil
}

type WatchSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Watches       []*WatchField          `protobuf:"bytes,2,rep,name=watches,proto3" json:"watches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchSpec) Reset() {
	*x = WatchSpec{}
	mi := &file_snes_live_v1_live_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSpec) ProtoMessage() {}

func (x *WatchSpec) ProtoReflect() protoreflect.Message {
	mi := &file_snes_live_v1_live_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSpec.ProtoReflect.Descriptor instead.
func (*WatchSpec) Descriptor() ([]byte, []int) {
	return file_snes_live_v1_live_proto_rawDescGZIP(), []int{18}
}

func (x *WatchSpec) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WatchSpec) GetWatches() []*WatchField {
	if x != nil {
		return x.Watches
	}
	return nil
}

type WatchField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Space         string                 `protobuf:"bytes,2,opt,name=space,proto3" json:"space,omitempty"`
	Addr          uint32                 `protobuf:"varint,3,opt,name=addr,proto3" json:"addr,omitempty"`
	Width         uint32                 `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchField) Reset() {
	*x = WatchField{}
	mi := &file_snes_live_v1_live_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchField) ProtoMessage() {}

func (x *WatchField) ProtoReflect() protoreflect.Message {
	mi := &file_snes_live_v1_live_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchField.ProtoReflect.Descriptor instead.
func (*WatchField) Descriptor() ([]byte, []int) {
	return file_snes_live_v1_live_proto_rawDescGZIP(), []int{19}
}

func (x *WatchField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WatchField) GetSpace() string {
	if x != nil {
		return x.Space
	}
	return ""
}

func (x *WatchField) GetAddr() uint32 {
	if x != nil {
		return x.Addr
	}
	return 0
}

func (x *WatchField) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

type ReadWatchesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WatchSpec     *WatchSpec             `protobuf:"bytes,1,opt,name=watch_spec,json=watchSpec,proto3" json:"watch_spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadWatchesRequest) Reset() {
	*x = ReadWatchesRequest{}
	mi := &file_snes_live_v1_live_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadWatchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadWatchesRequest) ProtoMessage() {}

func (x *ReadWatchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snes_live_v1_live_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadWatchesRequest.ProtoReflect.Descriptor instead.
func (*ReadWatchesRequest) Descriptor() ([]byte, []int) {
	return file_snes_live_v1_live_proto_rawDescGZIP(), []int{20}
}

func (x *ReadWatchesRequest) GetWatchSpec() *WatchSpec {
	if x != nil {
		return x.WatchSpec
	}
	return nil
}

type ReadWatchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Watches       map[string]uint64      `protobuf:"bytes,1,rep,name=watches,proto3" json:"watches,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadWatchesResponse) Reset() {
	*x = ReadWatchesResponse{}
	mi := &file_snes_live_v1_live_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadWatchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadWatchesResponse) ProtoMessage() {}

func (x *ReadWatchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snes_live_v1_live_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadWatchesResponse.ProtoReflect.Descriptor instead.
func (*ReadWatchesResponse) Descriptor() ([]byte, []int) {
	return file_snes_live_v1_live_proto_rawDescGZIP(), []int{21}
}

func (x *ReadWatchesResponse) GetWatches() map[string]uint64 {
	if x != nil {
		return x.Watches
	}
	return nil
}

type ReadMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Space         string                 `protobuf:"bytes,1,opt,name=space,proto3" json:"space,omitempty"`
	Addr          uint32                 `protobuf:"varint,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Length        uint32                 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadMemoryRequest) Reset() {
	*x = ReadMemoryRequest{}
	mi := &file_snes_live_v1_live_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMemoryRequest) ProtoMessage() {}

func (x *ReadMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snes_live_v1_live_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMemoryRequest.ProtoReflect.Descriptor instead.
func (*ReadMemoryRequest) Descriptor() ([]byte, []int) {
	return file_snes_live_v1_live_proto_rawDescGZIP(), []int{22}
}

func (x *ReadMemoryRequest) GetSpace() string {
	if x != nil {
		return x.Space
	}
	return ""
}

func (x *ReadMemoryRequest) GetAddr() uint32 {
	if x != nil {
		return x.Addr
	}
	return 0
}

func (x *ReadMemoryRequest) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type ReadMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Space         string                 `protobuf:"bytes,1,opt,name=space,proto3" json:"space,omitempty"`
	Addr          uint32                 `protobuf:"varint,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Bytes         uint32                 `protobuf:"varint,3,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Hash          string                 `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	Format        string                 `protobuf:"bytes,6,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadMemoryResponse) Reset() {
	*x = ReadMemoryResponse{}
	mi := &file_snes_live_v1_live_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMemoryResponse) ProtoMessage() {}

func (x *ReadMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snes_live_v1_live_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMemoryResponse.ProtoReflect.Descriptor instead.
func (*ReadMemoryResponse) Descriptor() ([]byte, []int) {
	return file_snes_live_v1_live_proto_rawDescGZIP(), []int{23}
}

func (x *ReadMemoryResponse) GetSpace() string {
	if x != nil {
		return x.Space
	}
	return ""
}

func (x *ReadMemoryResponse) GetAddr() uint32 {
	if x != nil {
		return x.Addr
	}
	return 0
}

func (x *ReadMemoryResponse) GetBytes() uint32 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *ReadMemoryResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReadMemoryResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ReadMemoryResponse) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type SnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_snes_live_v1_live_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snes_live_v1_live_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_snes_live_v1_live_proto_rawDescGZIP(), []int{24}
}

func (x *SnapshotRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checkpoint    *Checkpoint            `protobuf:"bytes,1,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	mi := &file_snes_live_v1_live_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snes_live_v1_live_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_snes_live_v1_live_proto_rawDescGZIP(), []int{25}
}

func (x *SnapshotResponse) GetCheckpoint() *Checkpoint {
	if x != nil {
		return x.Checkpoint
	}
	return nil
}

type RestoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checkpoint    string                 `protobuf:"bytes,1,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_snes_live_v1_live_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snes_live_v1_live_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_snes_live_v1_live_proto_rawDescGZIP(), []int{26}
}

func (x *RestoreRequest) GetCheckpoint() string {
	if x != nil {
		return x.Checkpoint
	}
	return ""
}

type RestoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreResponse) Reset() {
	*x = RestoreResponse{}
	mi := &file_snes_live_v1_live_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreResponse) ProtoMessage() {}

func (x *RestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snes_live_v1_live_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreResponse.ProtoReflect.Descriptor instead.
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return file_snes_live_v1_live_proto_rawDescGZIP(), []int{27}
}

func (x *RestoreResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type ForkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checkpoint    string                 `protobuf:"bytes,1,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForkRequest) Reset() {
	*x = ForkRequest{}
	mi := &file_snes_live_v1_live_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForkRequest) ProtoMessage() {}

func (x *ForkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snes_live_v1_live_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForkRequest.ProtoReflect.Descriptor instead.
func (*ForkRequest) Descriptor() ([]byte, []int) {
	return file_snes_live_v1_live_proto_rawDescGZIP(), []int{28}
}

func (x *ForkRequest) GetCheckpoint() string {
	if x != nil {
		return x.Checkpoint
	}
	return ""
}

func (x *ForkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ForkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checkpoint    *Checkpoint            `protobuf:"bytes,1,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForkResponse) Reset() {
	*x = ForkResponse{}
	mi := &file_snes_live_v1_live_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForkResponse) ProtoMessage() {}

func (x *ForkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snes_live_v1_live_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForkResponse.ProtoReflect.Descriptor instead.
func (*ForkResponse) Descriptor() ([]byte, []int) {
	return file_snes_live_v1_live_proto_rawDescGZIP(), []int{29}
}

func (x *ForkResponse) GetCheckpoint() *Checkpoint {
	if x != nil {
		return x.Checkpoint
	}
	return nil
}

type Checkpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Bytes         uint64                 `protobuf:"varint,3,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Checkpoint) Reset() {
	*x = Checkpoint{}
	mi := &file_snes_live_v1_live_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkpoint) ProtoMessage() {}

func (x *Checkpoint) ProtoReflect() protoreflect.Message {
	mi := &file_snes_live_v1_live_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkpoint.ProtoReflect.Descriptor instead.
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return file_snes_live_v1_live_proto_rawDescGZIP(), []int{30}
}

func (x *Checkpoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Checkpoint) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Checkpoint) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

type Status struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	RomPath         string                 `protobuf:"bytes,2,opt,name=rom_path,json=romPath,proto3" json:"rom_path,omitempty"`
	FramebufferHash string                 `protobuf:"bytes,3,opt,name=framebuffer_hash,json=framebufferHash,proto3" json:"framebuffer_hash,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_snes_live_v1_live_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_snes_live_v1_live_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_snes_live_v1_live_proto_rawDescGZIP(), []int{31}
}

func (x *Status) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Status) GetRomPath() string {
	if x != nil {
		return x.RomPath
	}
	return ""
}

func (x *Status) GetFramebufferHash() string {
	if x != nil {
		return x.FramebufferHash
	}
	return ""
}

var File_snes_live_v1_live_proto protoreflect.FileDescriptor

const file_snes_live_v1_live_proto_rawDesc = "" +
	"\n" +
	"\x17snes/live/v1/live.proto\x12\fsnes.live.v1\"$\n" +
	"\x0eLoadROMRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"?\n" +
	"\x0fLoadROMResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.snes.live.v1.StatusR\x06status\"_\n" +
	"\x10LoadStateRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x127\n" +
	"\x18allow_state_rom_mismatch\x18\x02 \x01(\bR\x15allowStateRomMismatch\"A\n" +
	"\x11LoadStateResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.snes.live.v1.StatusR\x06status\"\x0e\n" +
	"\fResetRequest\"=\n" +
	"\rResetResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.snes.live.v1.StatusR\x06status\"'\n" +
	"\x0fSetInputRequest\x12\x14\n" +
	"\x05input\x18\x01 \x01(\rR\x05input\"@\n" +
	"\x10SetInputResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.snes.live.v1.StatusR\x06status\"\x95\x01\n" +
	"\vStepRequest\x12\x16\n" +
	"\x06frames\x18\x01 \x01(\rR\x06frames\x12\x14\n" +
	"\x05input\x18\x02 \x01(\rR\x05input\x126\n" +
	"\n" +
	"watch_spec\x18\x03 \x01(\v2\x17.snes.live.v1.WatchSpecR\twatchSpec\x12 \n" +
	"\vframebuffer\x18\x04 \x01(\tR\vframebuffer\"\x85\x02\n" +
	"\fStepResponse\x12\x16\n" +
	"\x06frames\x18\x01 \x01(\rR\x06frames\x12\x14\n" +
	"\x05input\x18\x02 \x01(\rR\x05input\x12A\n" +
	"\awatches\x18\x03 \x03(\v2'.snes.live.v1.StepResponse.WatchesEntryR\awatches\x12)\n" +
	"\x10framebuffer_hash\x18\x04 \x01(\tR\x0fframebufferHash\x12\x1d\n" +
	"\n" +
	"frame_rgba\x18\x05 \x01(\fR\tframeRgba\x1a:\n" +
	"\fWatchesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"\x83\x02\n" +
	"\n" +
	"RunRequest\x12\x16\n" +
	"\x06frames\x18\x01 \x01(\rR\x06frames\x12\x19\n" +
	"\x05input\x18\x02 \x01(\rH\x00R\x05input\x88\x01\x01\x12%\n" +
	"\x0einput_sequence\x18\x03 \x03(\rR\rinputSequence\x126\n" +
	"\n" +
	"watch_spec\x18\x04 \x01(\v2\x17.snes.live.v1.WatchSpecR\twatchSpec\x12!\n" +
	"\fevent_filter\x18\x05 \x03(\tR\veventFilter\x12 \n" +
	"\vframebuffer\x18\x06 \x01(\tR\vframebuffer\x12\x14\n" +
	"\x05every\x18\a \x01(\rR\x05everyB\b\n" +
	"\x06_input\">\n" +
	"\vRunResponse\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.snes.live.v1.RunResultR\x06result\"\xd7\x04\n" +
	"\tRunResult\x12\x16\n" +
	"\x06frames\x18\x01 \x01(\rR\x06frames\x12\x1d\n" +
	"\n" +
	"input_hash\x18\x02 \x01(\tR\tinputHash\x12!\n" +
	"\fevent_filter\x18\x03 \x03(\tR\veventFilter\x12>\n" +
	"\awatches\x18\x04 \x03(\v2$.snes.live.v1.RunResult.WatchesEntryR\awatches\x12)\n" +
	"\x10framebuffer_hash\x18\x05 \x01(\tR\x0fframebufferHash\x12W\n" +
	"\x10component_hashes\x18\x06 \x03(\v2,.snes.live.v1.RunResult.ComponentHashesEntryR\x0fcomponentHashes\x12(\n" +
	"\x10final_state_hash\x18\a \x01(\tR\x0efinalStateHash\x12\x1d\n" +
	"\n" +
	"frame_rgba\x18\b \x01(\fR\tframeRgba\x12C\n" +
	"\x0fframe_summaries\x18\t \x03(\v2\x1a.snes.live.v1.FrameSummaryR\x0eframeSummaries\x12\x1e\n" +
	"\n" +
	"checkpoint\x18\n" +
	" \x01(\tR\n" +
	"checkpoint\x1a:\n" +
	"\fWatchesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1aB\n" +
	"\x14ComponentHashesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\">\n" +
	"\x10RunStreamRequest\x12*\n" +
	"\x03run\x18\x01 \x01(\v2\x18.snes.live.v1.RunRequestR\x03run\"\xde\x01\n" +
	"\x18RunFromCheckpointRequest\x12\x1e\n" +
	"\n" +
	"checkpoint\x18\x01 \x01(\tR\n" +
	"checkpoint\x12%\n" +
	"\x0einput_sequence\x18\x02 \x03(\rR\rinputSequence\x126\n" +
	"\n" +
	"watch_spec\x18\x03 \x01(\v2\x17.snes.live.v1.WatchSpecR\twatchSpec\x12!\n" +
	"\fevent_filter\x18\x04 \x03(\tR\veventFilter\x12 \n" +
	"\vframebuffer\x18\x05 \x01(\tR\vframebuffer\"L\n" +
	"\x19RunFromCheckpointResponse\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.snes.live.v1.RunResultR\x06result\"\x81\x01\n" +
	"\x11RunStreamResponse\x122\n" +
	"\x05frame\x18\x01 \x01(\v2\x1a.snes.live.v1.FrameSummaryH\x00R\x05frame\x12/\n" +
	"\x05final\x18\x02 \x01(\v2\x17.snes.live.v1.RunResultH\x00R\x05finalB\a\n" +
	"\x05event\"\x84\x03\n" +
	"\fFrameSummary\x12\x14\n" +
	"\x05frame\x18\x01 \x01(\rR\x05frame\x12\x14\n" +
	"\x05input\x18\x02 \x01(\rR\x05input\x12A\n" +
	"\awatches\x18\x03 \x03(\v2'.snes.live.v1.FrameSummary.WatchesEntryR\awatches\x12)\n" +
	"\x10framebuffer_hash\x18\x04 \x01(\tR\x0fframebufferHash\x12Z\n" +
	"\x10component_hashes\x18\x05 \x03(\v2/.snes.live.v1.FrameSummary.ComponentHashesEntryR\x0fcomponentHashes\x1a:\n" +
	"\fWatchesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1aB\n" +
	"\x14ComponentHashesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"S\n" +
	"\tWatchSpec\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x122\n" +
	"\awatches\x18\x02 \x03(\v2\x18.snes.live.v1.WatchFieldR\awatches\"`\n" +
	"\n" +
	"WatchField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05space\x18\x02 \x01(\tR\x05space\x12\x12\n" +
	"\x04addr\x18\x03 \x01(\rR\x04addr\x12\x14\n" +
	"\x05width\x18\x04 \x01(\rR\x05width\"L\n" +
	"\x12ReadWatchesRequest\x126\n" +
	"\n" +
	"watch_spec\x18\x01 \x01(\v2\x17.snes.live.v1.WatchSpecR\twatchSpec\"\x9b\x01\n" +
	"\x13ReadWatchesResponse\x12H\n" +
	"\awatches\x18\x01 \x03(\v2..snes.live.v1.ReadWatchesResponse.WatchesEntryR\awatches\x1a:\n" +
	"\fWatchesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"U\n" +
	"\x11ReadMemoryRequest\x12\x14\n" +
	"\x05space\x18\x01 \x01(\tR\x05space\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\rR\x04addr\x12\x16\n" +
	"\x06length\x18\x03 \x01(\rR\x06length\"\x94\x01\n" +
	"\x12ReadMemoryResponse\x12\x14\n" +
	"\x05space\x18\x01 \x01(\tR\x05space\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\rR\x04addr\x12\x14\n" +
	"\x05bytes\x18\x03 \x01(\rR\x05bytes\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x12\n" +
	"\x04hash\x18\x05 \x01(\tR\x04hash\x12\x16\n" +
	"\x06format\x18\x06 \x01(\tR\x06format\"%\n" +
	"\x0fSnapshotRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"L\n" +
	"\x10SnapshotResponse\x128\n" +
	"\n" +
	"checkpoint\x18\x01 \x01(\v2\x18.snes.live.v1.CheckpointR\n" +
	"checkpoint\"0\n" +
	"\x0eRestoreRequest\x12\x1e\n" +
	"\n" +
	"checkpoint\x18\x01 \x01(\tR\n" +
	"checkpoint\"?\n" +
	"\x0fRestoreResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.snes.live.v1.StatusR\x06status\"A\n" +
	"\vForkRequest\x12\x1e\n" +
	"\n" +
	"checkpoint\x18\x01 \x01(\tR\n" +
	"checkpoint\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"H\n" +
	"\fForkResponse\x128\n" +
	"\n" +
	"checkpoint\x18\x01 \x01(\v2\x18.snes.live.v1.CheckpointR\n" +
	"checkpoint\"J\n" +
	"\n" +
	"Checkpoint\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x14\n" +
	"\x05bytes\x18\x03 \x01(\x04R\x05bytes\"f\n" +
	"\x06Status\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x19\n" +
	"\brom_path\x18\x02 \x01(\tR\aromPath\x12)\n" +
	"\x10framebuffer_hash\x18\x03 \x01(\tR\x0fframebufferHash2\xdc\a\n" +
	"\x0fSNESLiveService\x12F\n" +
	"\aLoadROM\x12\x1c.snes.live.v1.LoadROMRequest\x1a\x1d.snes.live.v1.LoadROMResponse\x12L\n" +
	"\tLoadState\x12\x1e.snes.live.v1.LoadStateRequest\x1a\x1f.snes.live.v1.LoadStateResponse\x12@\n" +
	"\x05Reset\x12\x1a.snes.live.v1.ResetRequest\x1a\x1b.snes.live.v1.ResetResponse\x12I\n" +
	"\bSetInput\x12\x1d.snes.live.v1.SetInputRequest\x1a\x1e.snes.live.v1.SetInputResponse\x12=\n" +
	"\x04Step\x12\x19.snes.live.v1.StepRequest\x1a\x1a.snes.live.v1.StepResponse\x12:\n" +
	"\x03Run\x12\x18.snes.live.v1.RunRequest\x1a\x19.snes.live.v1.RunResponse\x12N\n" +
	"\tRunStream\x12\x1e.snes.live.v1.RunStreamRequest\x1a\x1f.snes.live.v1.RunStreamResponse0\x01\x12R\n" +
	"\vReadWatches\x12 .snes.live.v1.ReadWatchesRequest\x1a!.snes.live.v1.ReadWatchesResponse\x12O\n" +
	"\n" +
	"ReadMemory\x12\x1f.snes.live.v1.ReadMemoryRequest\x1a .snes.live.v1.ReadMemoryResponse\x12I\n" +
	"\bSnapshot\x12\x1d.snes.live.v1.SnapshotRequest\x1a\x1e.snes.live.v1.SnapshotResponse\x12F\n" +
	"\aRestore\x12\x1c.snes.live.v1.RestoreRequest\x1a\x1d.snes.live.v1.RestoreResponse\x12=\n" +
	"\x04Fork\x12\x19.snes.live.v1.ForkRequest\x1a\x1a.snes.live.v1.ForkResponse\x12d\n" +
	"\x11RunFromCheckpoint\x12&.snes.live.v1.RunFromCheckpointRequest\x1a'.snes.live.v1.RunFromCheckpointResponseB5Z3github.com/tmc/snes/internal/sneslive/v1;sneslivev1b\x06proto3"

var (
	file_snes_live_v1_live_proto_rawDescOnce sync.Once
	file_snes_live_v1_live_proto_rawDescData []byte
)

func file_snes_live_v1_live_proto_rawDescGZIP() []byte {
	file_snes_live_v1_live_proto_rawDescOnce.Do(func() {
		file_snes_live_v1_live_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_snes_live_v1_live_proto_rawDesc), len(file_snes_live_v1_live_proto_rawDesc)))
	})
	return file_snes_live_v1_live_proto_rawDescData
}

var file_snes_live_v1_live_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_snes_live_v1_live_proto_goTypes = []any{
	(*LoadROMRequest)(nil),            // 0: snes.live.v1.LoadROMRequest
	(*LoadROMResponse)(nil),           // 1: snes.live.v1.LoadROMResponse
	(*LoadStateRequest)(nil),          // 2: snes.live.v1.LoadStateRequest
	(*LoadStateResponse)(nil),         // 3: snes.live.v1.LoadStateResponse
	(*ResetRequest)(nil),              // 4: snes.live.v1.ResetRequest
	(*ResetResponse)(nil),             // 5: snes.live.v1.ResetResponse
	(*SetInputRequest)(nil),           // 6: snes.live.v1.SetInputRequest
	(*SetInputResponse)(nil),          // 7: snes.live.v1.SetInputResponse
	(*StepRequest)(nil),               // 8: snes.live.v1.StepRequest
	(*StepResponse)(nil),              // 9: snes.live.v1.StepResponse
	(*RunRequest)(nil),                // 10: snes.live.v1.RunRequest
	(*RunResponse)(nil),               // 11: snes.live.v1.RunResponse
	(*RunResult)(nil),                 // 12: snes.live.v1.RunResult
	(*RunStreamRequest)(nil),          // 13: snes.live.v1.RunStreamRequest
	(*RunFromCheckpointRequest)(nil),  // 14: snes.live.v1.RunFromCheckpointRequest
	(*RunFromCheckpointResponse)(nil), // 15: snes.live.v1.RunFromCheckpointResponse
	(*RunStreamResponse)(nil),         // 16: snes.live.v1.RunStreamResponse
	(*FrameSummary)(nil),              // 17: snes.live.v1.FrameSummary
	(*WatchSpec)(nil),                 // 18: snes.live.v1.WatchSpec
	(*WatchField)(nil),                // 19: snes.live.v1.WatchField
	(*ReadWatchesRequest)(nil),        // 20: snes.live.v1.ReadWatchesRequest
	(*ReadWatchesResponse)(nil),       // 21: snes.live.v1.ReadWatchesResponse
	(*ReadMemoryRequest)(nil),         // 22: snes.live.v1.ReadMemoryRequest
	(*ReadMemoryResponse)(nil),        // 23: snes.live.v1.ReadMemoryResponse
	(*SnapshotRequest)(nil),           // 24: snes.live.v1.SnapshotRequest
	(*SnapshotResponse)(nil),          // 25: snes.live.v1.SnapshotResponse
	(*RestoreRequest)(nil),            // 26: snes.live.v1.RestoreRequest
	(*RestoreResponse)(nil),           // 27: snes.live.v1.RestoreResponse
	(*ForkRequest)(nil),               // 28: snes.live.v1.ForkRequest
	(*ForkResponse)(nil),              // 29: snes.live.v1.ForkResponse
	(*Checkpoint)(nil),                // 30: snes.live.v1.Checkpoint
	(*Status)(nil),                    // 31: snes.live.v1.Status
	nil,                               // 32: snes.live.v1.StepResponse.WatchesEntry
	nil,                               // 33: snes.live.v1.RunResult.WatchesEntry
	nil,                               // 34: snes.live.v1.RunResult.ComponentHashesEntry
	nil,                               // 35: snes.live.v1.FrameSummary.WatchesEntry
	nil,                               // 36: snes.live.v1.FrameSummary.ComponentHashesEntry
	nil,                               // 37: snes.live.v1.ReadWatchesResponse.WatchesEntry
}
var file_snes_live_v1_live_proto_depIdxs = []int32{
	31, // 0: snes.live.v1.LoadROMResponse.status:type_name -> snes.live.v1.Status
	31, // 1: snes.live.v1.LoadStateResponse.status:type_name -> snes.live.v1.Status
	31, // 2: snes.live.v1.ResetResponse.status:type_name -> snes.live.v1.Status
	31, // 3: snes.live.v1.SetInputResponse.status:type_name -> snes.live.v1.Status
	18, // 4: snes.live.v1.StepRequest.watch_spec:type_name -> snes.live.v1.WatchSpec
	32, // 5: snes.live.v1.StepResponse.watches:type_name -> snes.live.v1.StepResponse.WatchesEntry
	18, // 6: snes.live.v1.RunRequest.watch_spec:type_name -> snes.live.v1.WatchSpec
	12, // 7: snes.live.v1.RunResponse.result:type_name -> snes.live.v1.RunResult
	33, // 8: snes.live.v1.RunResult.watches:type_name -> snes.live.v1.RunResult.WatchesEntry
	34, // 9: snes.live.v1.RunResult.component_hashes:type_name -> snes.live.v1.RunResult.ComponentHashesEntry
	17, // 10: snes.live.v1.RunResult.frame_summaries:type_name -> snes.live.v1.FrameSummary
	10, // 11: snes.live.v1.RunStreamRequest.run:type_name -> snes.live.v1.RunRequest
	18, // 12: snes.live.v1.RunFromCheckpointRequest.watch_spec:type_name -> snes.live.v1.WatchSpec
	12, // 13: snes.live.v1.RunFromCheckpointResponse.result:type_name -> snes.live.v1.RunResult
	17, // 14: snes.live.v1.RunStreamResponse.frame:type_name -> snes.live.v1.FrameSummary
	12, // 15: snes.live.v1.RunStreamResponse.final:type_name -> snes.live.v1.RunResult
	35, // 16: snes.live.v1.FrameSummary.watches:type_name -> snes.live.v1.FrameSummary.WatchesEntry
	36, // 17: snes.live.v1.FrameSummary.component_hashes:type_name -> snes.live.v1.FrameSummary.ComponentHashesEntry
	19, // 18: snes.live.v1.WatchSpec.watches:type_name -> snes.live.v1.WatchField
	18, // 19: snes.live.v1.ReadWatchesRequest.watch_spec:type_name -> snes.live.v1.WatchSpec
	37, // 20: snes.live.v1.ReadWatchesResponse.watches:type_name -> snes.live.v1.ReadWatchesResponse.WatchesEntry
	30, // 21: snes.live.v1.SnapshotResponse.checkpoint:type_name -> snes.live.v1.Checkpoint
	31, // 22: snes.live.v1.RestoreResponse.status:type_name -> snes.live.v1.Status
	30, // 23: snes.live.v1.ForkResponse.checkpoint:type_name -> snes.live.v1.Checkpoint
	0,  // 24: snes.live.v1.SNESLiveService.LoadROM:input_type -> snes.live.v1.LoadROMRequest
	2,  // 25: snes.live.v1.SNESLiveService.LoadState:input_type -> snes.live.v1.LoadStateRequest
	4,  // 26: snes.live.v1.SNESLiveService.Reset:input_type -> snes.live.v1.ResetRequest
	6,  // 27: snes.live.v1.SNESLiveService.SetInput:input_type -> snes.live.v1.SetInputRequest
	8,  // 28: snes.live.v1.SNESLiveService.Step:input_type -> snes.live.v1.StepRequest
	10, // 29: snes.live.v1.SNESLiveService.Run:input_type -> snes.live.v1.RunRequest
	13, // 30: snes.live.v1.SNESLiveService.RunStream:input_type -> snes.live.v1.RunStreamRequest
	20, // 31: snes.live.v1.SNESLiveService.ReadWatches:input_type -> snes.live.v1.ReadWatchesRequest
	22, // 32: snes.live.v1.SNESLiveService.ReadMemory:input_type -> snes.live.v1.ReadMemoryRequest
	24, // 33: snes.live.v1.SNESLiveService.Snapshot:input_type -> snes.live.v1.SnapshotRequest
	26, // 34: snes.live.v1.SNESLiveService.Restore:input_type -> snes.live.v1.RestoreRequest
	28, // 35: snes.live.v1.SNESLiveService.Fork:input_type -> snes.live.v1.ForkRequest
	14, // 36: snes.live.v1.SNESLiveService.RunFromCheckpoint:input_type -> snes.live.v1.RunFromCheckpointRequest
	1,  // 37: snes.live.v1.SNESLiveService.LoadROM:output_type -> snes.live.v1.LoadROMResponse
	3,  // 38: snes.live.v1.SNESLiveService.LoadState:output_type -> snes.live.v1.LoadStateResponse
	5,  // 39: snes.live.v1.SNESLiveService.Reset:output_type -> snes.live.v1.ResetResponse
	7,  // 40: snes.live.v1.SNESLiveService.SetInput:output_type -> snes.live.v1.SetInputResponse
	9,  // 41: snes.live.v1.SNESLiveService.Step:output_type -> snes.live.v1.StepResponse
	11, // 42: snes.live.v1.SNESLiveService.Run:output_type -> snes.live.v1.RunResponse
	16, // 43: snes.live.v1.SNESLiveService.RunStream:output_type -> snes.live.v1.RunStreamResponse
	21, // 44: snes.live.v1.SNESLiveService.ReadWatches:output_type -> snes.live.v1.ReadWatchesResponse
	23, // 45: snes.live.v1.SNESLiveService.ReadMemory:output_type -> snes.live.v1.ReadMemoryResponse
	25, // 46: snes.live.v1.SNESLiveService.Snapshot:output_type -> snes.live.v1.SnapshotResponse
	27, // 47: snes.live.v1.SNESLiveService.Restore:output_type -> snes.live.v1.RestoreResponse
	29, // 48: snes.live.v1.SNESLiveService.Fork:output_type -> snes.live.v1.ForkResponse
	15, // 49: snes.live.v1.SNESLiveService.RunFromCheckpoint:output_type -> snes.live.v1.RunFromCheckpointResponse
	37, // [37:50] is the sub-list for method output_type
	24, // [24:37] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_snes_live_v1_live_proto_init() }
func file_snes_live_v1_live_proto_init() {
	if File_snes_live_v1_live_proto != nil {
		return
	}
	file_snes_live_v1_live_proto_msgTypes[10].OneofWrappers = []any{}
	file_snes_live_v1_live_proto_msgTypes[16].OneofWrappers = []any{
		(*RunStreamResponse_Frame)(nil),
		(*RunStreamResponse_Final)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_snes_live_v1_live_proto_rawDesc), len(file_snes_live_v1_live_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_snes_live_v1_live_proto_goTypes,
		DependencyIndexes: file_snes_live_v1_live_proto_depIdxs,
		MessageInfos:      file_snes_live_v1_live_proto_msgTypes,
	}.Build()
	File_snes_live_v1_live_proto = out.File
	file_snes_live_v1_live_proto_goTypes = nil
	file_snes_live_v1_live_proto_depIdxs = nil
}
